/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_videgro_ships_bridge_NativeRtlSdr */

#ifndef _Included_net_videgro_ships_bridge_NativeRtlSdr
#define _Included_net_videgro_ships_bridge_NativeRtlSdr
#ifdef __cplusplus
extern "C" {
#endif
#undef net_videgro_ships_bridge_NativeRtlSdr_WAIT_TIME
#define net_videgro_ships_bridge_NativeRtlSdr_WAIT_TIME 5000L
/*
 * Class:     net_videgro_ships_bridge_NativeRtlSdr
 * Method:    startRtlSdrAis
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_videgro_ships_bridge_NativeRtlSdr_startRtlSdrAis
  (JNIEnv *, jclass, jstring, jint, jstring);

/*
 * Class:     net_videgro_ships_bridge_NativeRtlSdr
 * Method:    stopRtlSdrAis
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_videgro_ships_bridge_NativeRtlSdr_stopRtlSdrAis
  (JNIEnv *, jclass);

/*
 * Class:     net_videgro_ships_bridge_NativeRtlSdr
 * Method:    changeRtlSdrPpm
 */
JNIEXPORT void JNICALL Java_net_videgro_ships_bridge_NativeRtlSdr_changeRtlSdrPpm
  (JNIEnv *, jclass,jint);


/*
 * Class:     net_videgro_ships_bridge_NativeRtlSdr
 * Method:    isRunningRtlSdrAis
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_videgro_ships_bridge_NativeRtlSdr_isRunningRtlSdrAis
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class net_videgro_ships_bridge_NativeRtlSdr_NativeRtlSdrListener */

#ifndef _Included_net_videgro_ships_bridge_NativeRtlSdr_NativeRtlSdrListener
#define _Included_net_videgro_ships_bridge_NativeRtlSdr_NativeRtlSdrListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
